# Generated by Django 5.2.3 on 2025-06-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_country", models.CharField(max_length=64)),
                ("destination", models.CharField(max_length=64)),
                ("Num_Of_Nights", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
